org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.141.6+1.21.11
simple_voice_chat_version=fabric-1.21.11-2.6.22
plasmo_voice_version=fabric-1.21.11-2.1.14

mod_version=1.6.1
maven_group=dev.openyourmouth
archives_base_name=openyourmouth
